version: '3.8'

services:
  sehati-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Tambahkan environment variable yang diperlukan
      # Server
      PORT: 3000
      HOST: 0.0.0.0

      # Database
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:

      # JWT
      JWT_SECRET:
    # volumes:
    #   - .:/app
    networks:
      - sehati-network
networks:
  sehati-network:
    external: true
  # Jika jaringan eksternal belum dibuat, Anda bisa membuatnya dengan perintah:
  # docker network create sehati-network